### ISSUE TITLE
create a form wrapper

### ISSUE THREAD

**Issue by adho12** [adho12/CMS#3]
**To-Do**
 - [ ] Form class
  - [X] Element class
    - [X] add JavaScript to the class
    - [X] add Css to the class
  - [ ] varius input type classes (extending the Element class)
    - [ ] Upload Class
    - [ ] custom HTML
    - [ ] Restet Class
    - [ ] Submit Class
